version: "3.8"

volumes:
    # mysqldata:
    # mysqlinit:
    app:

services:
    php:
        build: ./php
        ports:
            - 9438:80
        depends_on:
            - logstash
        restart: always
        volumes:
            - ./app:/var/www/html

    logstash:
        build: ./logstash
        ports:
            - 9001:9001
        restart: unless-stopped
        environment:
            LS_JAVA_OPTS: "-Xms500m -Xmx500m -XX:ParallelGCThreads=1"
        volumes:
            - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
            - "./logstash/logstash.conf:/usr/share/logstash/config/logstash_simple.conf"
        entrypoint:
            - logstash
            - -f
            - /usr/share/logstash/config/logstash_simple.conf

    # mysql:
    #     image: mysql:8
    #     ports:
    #         - 3306:3306
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: userpass
    #         MYSQL_DATABASE: testdb
    #     volumes:
    #         - ./mysql/initscripts:/docker-entrypoint-initdb.d
    #         - ./mysql/mysqldata:/var/lib/mysql/

    # adminer:
    #     image: adminer
    #     ports:
    #         - 8080:8080
