version: "3.8"

volumes:
    # mysqldata:
    # mysqlinit:
    app:

networks:
    elk:
        driver: bridge
    backend:
        driver: bridge

services:
    php:
        build: ./php
        ports:
            - ${PHP_PORT}:80
        depends_on:
            - logstash
        restart: always
        networks:
            - elk
            - backend
        volumes:
            - ./app:/var/www/html
        environment:
            - IS_LOGGING=${IS_LOGGING}
            - ROOT_PORT=${PHP_PORT}

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        networks:
            - elk
        environment:
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        mem_limit: ${MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        healthcheck:
            test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
            interval: 30s
            timeout: 10s
            retries: 50

    logstash:
        image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
        restart: unless-stopped
        environment:
            LS_JAVA_OPTS: "-Xms500m -Xmx500m -XX:ParallelGCThreads=1"
        mem_limit: ${MEM_LIMIT}
        volumes:
            - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml"
            - "./logstash/logstash.conf:/usr/share/logstash/config/logstash_simple.conf"
        depends_on:
            elasticsearch:
                condition: service_healthy
        networks:
            - elk
        entrypoint:
            - logstash
            - -f
            - /usr/share/logstash/config/logstash_simple.conf

    kibana:
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
        restart: unless-stopped
        ports:
            - ${KIBANA_PORT}:5601
        depends_on:
            - php
            - elasticsearch
        networks:
            - elk
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
        mem_limit: ${MEM_LIMIT}
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120

    # mysql:
    #     image: mysql:8
    #     ports:
    #         - 3306:3306
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: userpass
    #         MYSQL_DATABASE: testdb
    #     volumes:
    #         - ./mysql/initscripts:/docker-entrypoint-initdb.d
    #         - ./mysql/mysqldata:/var/lib/mysql/

    # adminer:
    #     image: adminer
    #     ports:
    #         - 8080:8080
